// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  areaswecover: dynamic(() => import("./Areaswecover")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  process: dynamic(() => import("./Process")),
  quote: dynamic(() => import("./Quote")),
  servicecta: dynamic(() => import("./Servicecta")),
  testimonial: dynamic(() => import("./Testimonial")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  whysection: dynamic(() => import("./Whysection")),
};
